.TH AMG 1L
.SH NAME
amg \- areuh message generator
.SH SYNOPSIS
.B amg
[
.I first message
]
.SH DESCRIPTION
.I Amg
is a message table generator for the HP-71.
It reads on standard input a sequence of messages for the HP-71, one
per line, and writes on standard output the source code to be assembled
by
.BR aas (1L).
.PP
The message is specified with the following syntax :
.RS 5n
.nf
	label:message
.fi
.RE
where
.I label
is a symbolic label used by the assembler and
.I message
is the message itself. Beware of extraneous white spaces in the message.
.PP
Messages are chains of characters. Some characters have e special meaning:
.TP 15
.B [
Begins a
.I building block.
If this is a system building block,
.B amg
uses it. Otherwise, a new building block is created.
.TP
.B ]
Ends the building block.
.TP
.B ^
Marks an insertion point in the message. See IDS I for more information.
.TP
<backslash>
Cancels the special meaning of the next character or allow using a
non printable character by its octal value.
.PP
The HP-71 operating system uses 17 known building-blocks.
.B Amg
recognize them automatically. They are:
.RS 5n
.nf
 0	"Illegal "
 1	" Expected"
 2	" Not Found"
 3	"Context"
 4	"File"
 5	" w/o "
 6	"Invalid "
 7	"Stat"
 8	"Too "
 9	": Align then ENDLN"
10	"Transform"
11	"Inf"
12	" Input"
13	" Ovfl"
14	"Pull"
15	/* insert message : ### of ### */
16	" Protect"
.fi
.RE
.PP
.B Amg
defines the symbol
.B =MSGTBL
which is referenced in the haeder of the Lex file. User defined symbols
can be also exported only if preceded by
.B =
at the beginning of the label.
.PP
The following example is the message table of JPC Rom:
.RS 5n
.nf
=eHEAD:JPC 
=eDRIVE:Driver Lex File
=eNSTRG:Not Found
=eSTRUC:Structure Mismatch
=eIPRMP:[Invalid ]Prompt
=eIFMT:[Invalid ]Format
=eIDIM:#Dims
=eINOVR:Var[ Not Found]
=eSUN:Sun[day]
=eMON:Mon[day]
=eTUE:Tues[day]
=eWED:Wednes[day]
=eTHU:Thurs[day]
=eFRI:Fri[day]
=eSAT:Satur[day]
=eFNINT:Function Interrupted
=eOBSOL:Removed Keyword
=eCPYRG:(c) 1986, 1987, 1988 PPC-Paris
.fi
.RE
.SH DIAGNOSTICS
.PP
.B Amg
produces un error when no message conforms to the rule of the first
message (length must be a multiple of 4) but generates a source file anyway.
.SH AUTHORS
Pierre David,
Janick Taillandier.
.SH SEE ALSO
aas(1L),
ald(1L),
adp(1L),
cp71(1L).
.br
.I "IDS vol I"
for HP-71.
