.TH ADP 1L
.SH NAME
adp \- areuh intermediate object file dump
.SH SYNOPSIS
.B adp
file
.SH DESCRIPTION
.B Adp
displays data about the given intermediate object file.
In particular,
.B adp
displays the code size,
external symbols not defined in the file, as well as
expressions not resolved during assembly.
.PP
.B Adp
was developed for internal use and should not normally be used.
.SH AUTHORS
Pierre David,
Janick Taillandier.
.SH SEE ALSO
aas(1L),
ald(1L),
amg(1L).
.br
.I "IDS vol I"
for HP-71.
