.TH ADP 1L
.SH NAME
adp \- areuh intermediate file dump
.SH SYNOPSIS
.B adp
file
.SH DESCRIPTION
.I Adp
affiche des informations sur le fichier intermédiaire
spécifié.
En particulier,
.B adp
affiche la taille du code,
les symboles externes définis dans ce fichier, ainsi que
les expressions n'ayant pas pu être résolues à l'assemblage.
.PP
.B Adp
a été développé pour des besoins internes et ne doit normalement pas être
utilisé.
.SH AUTHORS
Pierre David
Janick Taillandier
.SH SEE ALSO
aas(1L),
ald(1L),
amg(1L),
cp71(1L).
.br
.I "IDS vol I"
for HP-71.
