.TH AAS 1L
.SH NAME
aas \- areuh assembler
.SH SYNOPSIS
.B aas
[
.B -p
] [
.B -l
.I page length
] [
.B -A
] [
.B -a
.I listing file
] [
.B -x
] [
.B -o
.I object file
] [ file1 ... filen ]
.SH DESCRIPTION
.I Aas
est le cross-assembleur pour le HP-71, qui prend un ou des
fichiers sources, les assemble et place dans le fichier objet
soit un Lex ou Bin complet, soit un fichier intermédiaire
pour édition de liens ultérieure (voir
.IR ald (1L)).
.PP
Les options sont :
.TP 17
.B -p
Utilisation interactive : demande les noms des fichiers
au clavier. Option par défaut lorsqu'il n'y a aucun paramètre.
.TP
.BI -l " page length"
La longueur des pages du
.I listing file
est fixée à
.I page length
lignes (72 par défaut).
.TP
.B -A
Génère un listing d'assemblage avec offset, codes hexadécimaux,
et texte source. Le listing est envoyé sur la sortie standard.
.TP
.BI -a " listing file"
Génère un listing d'assemblage dans le fichier
.IR "listing file" .
.TP
.I -x
Génère dans le
.I listing file
une table des références croisées, indiquant pour chaque
symbole sa valeur et les numéros des lignes y faisant
référence.
.TP
.BI -o " object file"
Place le code objet dans le fichier spécifié. Par défaut,
le nom est celui du fichier source avec le suffixe
.IR .as ,
remplacé par
.I .ao
en cas d'assemblage séparé, ou
.B lex
en assemblage complet. Si
.I object file
est un répertoire, le fichier est placé dans le répertoire
indiqué avec les règles de renommage ci-dessus (note :
c'est l'utilisation la plus simple lorsque plusieurs sources
sont donnés sur la ligne de commandes).
.SH AUTHORS
Pierre David
Janick Taillandier
.SH SEE ALSO
ald(1L),
adp(1L),
amg(1L),
cp71(1L).
.br
.I "IDS vol I"
for HP-71.
