.TH AAS 1L
.SH NAME
aas \- areuh assembler
.SH SYNOPSIS
.B aas
[
.B -p
] [
.B -l
.I page length
] [
.B -A
] [
.B -a
.I listing file
] [
.B -x
] [
.B -o
.I object file
] [ file1 ... filen ]
.SH DESCRIPTION
.I Aas
ss the cross-assembler for the HP-71. It takes one or more
source files, process them and produces an object file containig
either a LEX or BIN file (complete assembly), or an intermediate file 
to be used in the link phase (separate assembly). See
.IR ald (1L).
.PP
Options are :
.TP 17
.B -p
Interactive use :
.I Aas
prompts for the various file names. It is the default option
when no parameter is specified.
.TP
.BI -l " page length"
Page length of the 
.I listing file
is fixed by 
.I page length
lines (72 by default).
.TP
.B -A
Produces an assembly listing with offset, binary code in hexadecimal
and source code. The listing is sent to standard output.
.TP
.BI -a " listing file"
The assembly listing is sent to the file
.IR "listing file" .
.TP
.B -x
Adds a cross references table in the
.I listing file
showing for each symbol
its value and the line numbers where the symbol is referenced.
.TP
.BI -o " object file"
Writes the object code in the specified file. By default,
the objet file name is the name of the source file with
.IR .as ,
extension replaced by
.I .ao
in case of separate assembly, or
.I .lex
in case of complete assembly. If
.I object file
is a directory, the file is written in this directory and the
file name follows all the naming rules listed above.
It is the most convenient way to procede when assembling more
than one source file.
.SH AUTHORS
Pierre David,
Janick Taillandier.
.SH SEE ALSO
ald(1L),
adp(1L),
amg(1L).
.br
.I "IDS vol I"
for HP-71.
