.TH ALD 1L
.SH NAME
ald \- areuh link editor
.SH SYNOPSIS
.B ald
[
.B -p
] [
.B -l
.I page length
] [
.B -A
] [
.B -a
.I listing file
] [
.B -x
] [
.B -o
.I object file
] [ file1 ... filen ]
.SH DESCRIPTION
.I Ald
is the cross link editor for the HP-71. It combines one or more 
intermediate object files, resolves references and output an object file
ready to be be loaded in the HP-71.
.PP
The options are :
.TP 17
.B -p
Interactive use :
.I ald
prompts for the various file names. It is the default option
when no parameter is specified.
.TP
.BI -l " page length"
Page length for the
.I listing file
is set to
.I page length
lines (72 by default).
.TP
.B -A
Produces a link listing with symbol table.
The listing is sent to standard output.
.TP
.BI -a " listing file"
The link listing is sent to file
.IR "listing file" .
.TP
.B -x
Adds in the 
.I listing file
a cross reference table giving for each symbol its value and
offsets in the various intermediate files where the symbol
is used.
.TP
.BI -o " object file"
Stores the object file in the given file
(by default 
.B lex).
.SH AUTHORS
Pierre David,
Janick Taillandier.
.SH SEE ALSO
aas(1L),
adp(1L),
amg(1L),
cp71(1L).
.br
.I "IDS vol I"
for HP-71.
